[enh] Update Roundcube to 1.1.x with package refactoring
 * Remove upstream sources from repository except for ldapAliasSync
   plugin which need package fixes. Roundcube source tarball is retrieved
   from GitHub instead and dependencies are installed with composer.
 * Make use of app helpers provided by YunoHost and update scripts to fit
   with new multi-instances behaviour, e.g. app_id is passed to scripts.
 * Review scripts to catch as much as possible commands errors to display
   proper error message and add a _common.sh script for common variables and
   functions.
 * Update Roundcube, nginx and php-fpm configurations.

Note that rcmcarddav plugin is not installed anymore for the moment and
backup/restore scripts has not been updated too. It is a work-in-progress.

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,65 +1,92 @@
 #!/bin/bash
 
-domain=$(sudo yunohost app setting roundcube domain)
-path=$(sudo yunohost app setting roundcube path)
+set -e
 
-deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
-db_user=roundcube
-db_pwd=$(sudo yunohost app setting roundcube mysqlpwd)
-db_file=../sources/SQL/mysql/$(ls -tr -1 ../sources/SQL/mysql | head -1)
+# Load common variables and helpers
+. ./_common.sh
 
-mysql -u $db_user -p$db_pwd $db_user < $db_file
+# Set app specific variables
+app=$1
+dbname=$app
+dbuser=$app
 
-mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/automatic_addressbook/SQL/mysql.initial.sql
+# Source app helpers
+. /usr/share/yunohost/apps/helpers
 
-final_path=/var/www/roundcube
-sudo mkdir -p $final_path
-sudo cp -a ../sources/* $final_path
-sudo cp ../conf/main.inc.php $final_path/config/
-sudo cp ../conf/main.inc.php $final_path/config/defaults.inc.php
-sudo cp ../conf/db.inc.php $final_path/config/
-sudo mv $final_path/plugins/managesieve/config.inc.php.dist $final_path/plugins/managesieve/config.inc.php
+# Retrieve app settings
+domain=$(ynh_app_setting_get $app domain)
+path=$(ynh_app_setting_get $app path)
+dbpass=$(ynh_app_setting_get $app mysqlpwd)
 
-sudo sed -i "s/rcmail-ynhDESkeyTOchange/$deskey/g" $final_path/config/main.inc.php
-sudo sed -i "s/yunouser/$db_user/g" $final_path/config/db.inc.php
-sudo sed -i "s/yunopass/$db_pwd/g" $final_path/config/db.inc.php
-sudo sed -i "s/yunobase/$db_user/g" $final_path/config/db.inc.php
+# Check destination directory
+DESTDIR="/var/www/$app"
+[[ ! -d $DESTDIR ]] && die \
+"The destination directory '$DESTDIR' does not exist.\
+ The app is not correctly installed, you should remove it first."
 
-# Install rcmcarddav if baikal is detected
-sudo yunohost app list -f baikal --json | grep '"installed": true'
-if [ "$?" -eq 0 ]; then
-  echo "Detected Baikal"
+# Create tmp directory and install app inside
+TMPDIR=$(ynh_mkdir_tmp)
+install_with_composer "$TMPDIR"
+cp ../sources/bin/installto.sh "${TMPDIR}/bin/"
 
-  caldavdomain=$(sudo yunohost app setting baikal domain)
-  caldavpath=$(sudo yunohost app setting baikal path)
-  caldavpath=${caldavpath%/}
+# Generate a new random DES key
+deskey=$(ynh_string_random 24)
 
-  sed -i "s@yuno_baikal_domain@$caldavdomain@g" ../conf/rcmcarddav.config.inc.php
-  sed -i "s@yuno_baikal_path@$caldavpath@g" ../conf/rcmcarddav.config.inc.php
-  sudo cp ../conf/rcmcarddav.config.inc.php $final_path/plugins/carddav/config.inc.php
+# Copy and set Roundcube configuration
+rc_conf="${TMPDIR}/config/config.inc.php"
+cp ../conf/config.inc.php "$rc_conf"
+sed -i "s/#DESKEY#/${deskey}/g" "$rc_conf"
+sed -i "s/#DBUSER#/${dbuser}/g" "$rc_conf"
+sed -i "s/#DBPASS#/${dbpass}/g" "$rc_conf"
+sed -i "s/#DBNAME#/${dbname}/g" "$rc_conf"
 
-  sudo sed -i "s@yuno_enable_carddav@True@g" $final_path/config/main.inc.php
+# Execute Roundcube update script
+sudo php "${TMPDIR}/bin/installto.sh" "$DESTDIR" --no-interaction \
+  || die "Unable to update Roundcube installation"
+(cd "$DESTDIR" && sudo php composer.phar update --quiet -n --no-dev) \
+  || die "Unable to update dependencies"
+rm -rf "$TMPDIR"
 
-  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql-drop.sql
-  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql.sql
-else
-  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql-drop.sql
-  sudo sed -i "s@yuno_enable_carddav@False@g" $final_path/config/main.inc.php
-fi
+## Install rcmcarddav if baikal is detected
+#sudo yunohost app list -f baikal --json | grep '"installed": true'
+#if [ "$?" -eq 0 ]; then
+#  echo "Detected Baikal"
+#
+#  caldavdomain=$(sudo yunohost app setting baikal domain)
+#  caldavpath=$(sudo yunohost app setting baikal path)
+#  caldavpath=${caldavpath%/}
+#
+#  sed -i "s@yuno_baikal_domain@$caldavdomain@g" ../conf/rcmcarddav.config.inc.php
+#  sed -i "s@yuno_baikal_path@$caldavpath@g" ../conf/rcmcarddav.config.inc.php
+#  sudo cp ../conf/rcmcarddav.config.inc.php $final_path/plugins/carddav/config.inc.php
+#
+#  sudo sed -i "s@yuno_enable_carddav@True@g" $final_path/config/main.inc.php
+#
+#  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql-drop.sql
+#  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql.sql
+#else
+#  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql-drop.sql
+#  sudo sed -i "s@yuno_enable_carddav@False@g" $final_path/config/main.inc.php
+#fi
 
-sudo mkdir -p $final_path/logs
-sudo chown -R www-data: $final_path
+# Fix installation directories and permissions
+sudo mkdir -p "${DESTDIR}/logs" "${DESTDIR}/temp"
+sudo chown -R www-data: "$DESTDIR"
 
-sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
-sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
-sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/roundcube.conf
+# Copy and set nginx configuration
+nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
+sed -i "s@#PATH#@${path}@g"        ../conf/nginx.conf
+sed -i "s@#DESTDIR#@${DESTDIR}/@g" ../conf/nginx.conf
+sudo cp ../conf/nginx.conf "$nginx_conf"
 
-sed -i "s@NAMETOCHANGE@roundcube@g" ../conf/php-fpm.conf
-finalphpconf=/etc/php5/fpm/pool.d/roundcube.conf
-sudo cp ../conf/php-fpm.conf $finalphpconf
-sudo chown root: $finalphpconf
-sudo chmod 644 $finalphpconf
+# Copy and set php-fpm configuration
+phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"
+sed -i "s@#POOLNAME#@${app}@g"     ../conf/php-fpm.conf
+sed -i "s@#DESTDIR#@${DESTDIR}/@g" ../conf/php-fpm.conf
+sudo cp ../conf/php-fpm.conf "$phpfpm_conf"
+sudo chown root: $phpfpm_conf
+sudo chmod 644 $phpfpm_conf
 
-sudo service php5-fpm restart
-sudo service nginx reload
-sudo yunohost app ssowatconf
+# Reload services
+sudo service php5-fpm restart || true
+sudo service nginx reload || true
